// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCP8URa2SbelW_GsyAFcR9mYYaITELFc',
    appId: '1:677940886357:android:71b83a6630131b37a24ddc',
    messagingSenderId: '677940886357',
    projectId: 'music-app-c0498',
    storageBucket: 'music-app-c0498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgBLq6P6TfBGH4OfZe8rNTp9xnpV3WLM',
    appId: '1:677940886357:ios:c3247f12cfeff327a24ddc',
    messagingSenderId: '677940886357',
    projectId: 'music-app-c0498',
    storageBucket: 'music-app-c0498.appspot.com',
    iosClientId: '677940886357-lkc2bkr5ar8gaijjvkp4denpndqkea2p.apps.googleusercontent.com',
    iosBundleId: 'com.music.app',
  );
}

// Platform  Firebase App Id
// android   1:677940886357:android:71b83a6630131b37a24ddc
// ios       1:677940886357:ios:c3247f12cfeff327a24ddc
